version: 2

build:
  apt_packages:
    - libnetcdf-dev
  tools:
    python: "3.10"

sphinx:
  fail_on_warning: false


python:
  install:
    - requirements: docs/docs_requirements.txt
    - method: pip
      path: .


formats:
  - pdf


submodules:
  include: all
  recursive: true




