version: 2

build:
  apt_packages:
    - libnetcdf-dev
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_install:
      -  sed -i '/dependencies = .*/,+25d' pyproject.toml 

sphinx:
  fail_on_warning: false


python:
  install:
    - requirements: docs/docs_requirements.txt
    - method: pip
      path: .


formats:
  - pdf


submodules:
  include: all
  recursive: true




