# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 500)
        MainWindow.setMinimumSize(QtCore.QSize(801, 0))
        MainWindow.setMaximumSize(QtCore.QSize(801, 500))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.doubleSpinBox_filteringCutoff = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_filteringCutoff.setGeometry(QtCore.QRect(460, 340, 62, 24))
        self.doubleSpinBox_filteringCutoff.setProperty("value", 20.0)
        self.doubleSpinBox_filteringCutoff.setObjectName("doubleSpinBox_filteringCutoff")
        self.lineEdit_residueGroup1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_residueGroup1.setGeometry(QtCore.QRect(250, 270, 271, 24))
        self.lineEdit_residueGroup1.setObjectName("lineEdit_residueGroup1")
        self.lineEdit_residueGroup2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_residueGroup2.setGeometry(QtCore.QRect(250, 300, 271, 24))
        self.lineEdit_residueGroup2.setObjectName("lineEdit_residueGroup2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 340, 231, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-30, 340, 171, 21))
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.doubleSpinBox_filteringPercent = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_filteringPercent.setGeometry(QtCore.QRect(150, 340, 62, 24))
        self.doubleSpinBox_filteringPercent.setProperty("value", 60.0)
        self.doubleSpinBox_filteringPercent.setObjectName("doubleSpinBox_filteringPercent")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(-20, 380, 161, 20))
        self.label_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.spinBox_numProcessors = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_numProcessors.setGeometry(QtCore.QRect(460, 380, 62, 24))
        self.spinBox_numProcessors.setProperty("value", 4)
        self.spinBox_numProcessors.setObjectName("spinBox_numProcessors")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 380, 151, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_Calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Calculate.setGeometry(QtCore.QRect(540, 130, 251, 61))
        self.pushButton_Calculate.setObjectName("pushButton_Calculate")
        self.progressBar_filtering = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_filtering.setGeometry(QtCore.QRect(540, 280, 251, 21))
        self.progressBar_filtering.setProperty("value", 0)
        self.progressBar_filtering.setObjectName("progressBar_filtering")
        self.progressBar_calculation = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_calculation.setGeometry(QtCore.QRect(540, 330, 251, 23))
        self.progressBar_calculation.setProperty("value", 0)
        self.progressBar_calculation.setObjectName("progressBar_calculation")
        self.pushButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop.setEnabled(False)
        self.pushButton_Stop.setGeometry(QtCore.QRect(540, 200, 251, 61))
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.labelFiltering = QtWidgets.QLabel(self.centralwidget)
        self.labelFiltering.setGeometry(QtCore.QRect(540, 260, 251, 21))
        self.labelFiltering.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFiltering.setObjectName("labelFiltering")
        self.labelCalculation = QtWidgets.QLabel(self.centralwidget)
        self.labelCalculation.setGeometry(QtCore.QRect(540, 310, 251, 20))
        self.labelCalculation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCalculation.setObjectName("labelCalculation")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(520, 0, 21, 491))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit_pdb = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pdb.setGeometry(QtCore.QRect(10, 50, 271, 21))
        self.lineEdit_pdb.setText("")
        self.lineEdit_pdb.setObjectName("lineEdit_pdb")
        self.lineEdit_psf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_psf.setGeometry(QtCore.QRect(10, 80, 271, 21))
        self.lineEdit_psf.setText("")
        self.lineEdit_psf.setObjectName("lineEdit_psf")
        self.lineEdit_dcd = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dcd.setGeometry(QtCore.QRect(10, 110, 271, 21))
        self.lineEdit_dcd.setText("")
        self.lineEdit_dcd.setObjectName("lineEdit_dcd")
        self.lineEdit_outputFolder = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_outputFolder.setGeometry(QtCore.QRect(10, 140, 271, 21))
        self.lineEdit_outputFolder.setObjectName("lineEdit_outputFolder")
        self.lineEdit_namd2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_namd2.setGeometry(QtCore.QRect(10, 170, 271, 21))
        self.lineEdit_namd2.setObjectName("lineEdit_namd2")
        self.pushButton_browsePDB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browsePDB.setGeometry(QtCore.QRect(290, 50, 231, 21))
        self.pushButton_browsePDB.setToolTipDuration(-1)
        self.pushButton_browsePDB.setObjectName("pushButton_browsePDB")
        self.pushButton_browsePSF = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browsePSF.setGeometry(QtCore.QRect(290, 80, 231, 21))
        self.pushButton_browsePSF.setObjectName("pushButton_browsePSF")
        self.pushButton_browseDCD = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browseDCD.setGeometry(QtCore.QRect(290, 110, 231, 21))
        self.pushButton_browseDCD.setObjectName("pushButton_browseDCD")
        self.pushButton_browseOutputFolder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browseOutputFolder.setGeometry(QtCore.QRect(290, 140, 231, 21))
        self.pushButton_browseOutputFolder.setObjectName("pushButton_browseOutputFolder")
        self.pushButton_BrowseNAMD = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BrowseNAMD.setGeometry(QtCore.QRect(290, 170, 231, 21))
        self.pushButton_BrowseNAMD.setObjectName("pushButton_BrowseNAMD")
        self.checkBox_interactionCorrelation = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_interactionCorrelation.setGeometry(QtCore.QRect(190, 420, 331, 21))
        self.checkBox_interactionCorrelation.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_interactionCorrelation.setObjectName("checkBox_interactionCorrelation")
        self.pushButton_BrowseParameterFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BrowseParameterFile.setGeometry(QtCore.QRect(290, 200, 231, 21))
        self.pushButton_BrowseParameterFile.setObjectName("pushButton_BrowseParameterFile")
        self.lineEdit_parameterFile = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_parameterFile.setGeometry(QtCore.QRect(10, 200, 271, 21))
        self.lineEdit_parameterFile.setText("")
        self.lineEdit_parameterFile.setObjectName("lineEdit_parameterFile")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(7, 400, 521, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.doubleSpinBox_AverageIntEnCutoff = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_AverageIntEnCutoff.setEnabled(False)
        self.doubleSpinBox_AverageIntEnCutoff.setGeometry(QtCore.QRect(460, 450, 62, 24))
        self.doubleSpinBox_AverageIntEnCutoff.setDecimals(2)
        self.doubleSpinBox_AverageIntEnCutoff.setMaximum(100.0)
        self.doubleSpinBox_AverageIntEnCutoff.setSingleStep(0.01)
        self.doubleSpinBox_AverageIntEnCutoff.setProperty("value", 1.0)
        self.doubleSpinBox_AverageIntEnCutoff.setObjectName("doubleSpinBox_AverageIntEnCutoff")
        self.label_PearsonCorrCutoff = QtWidgets.QLabel(self.centralwidget)
        self.label_PearsonCorrCutoff.setGeometry(QtCore.QRect(170, 450, 281, 20))
        self.label_PearsonCorrCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_PearsonCorrCutoff.setObjectName("label_PearsonCorrCutoff")
        self.labelCorrelation = QtWidgets.QLabel(self.centralwidget)
        self.labelCorrelation.setGeometry(QtCore.QRect(540, 360, 251, 20))
        self.labelCorrelation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCorrelation.setObjectName("labelCorrelation")
        self.progressBar_correlation = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_correlation.setGeometry(QtCore.QRect(540, 380, 251, 23))
        self.progressBar_correlation.setProperty("value", 0)
        self.progressBar_correlation.setObjectName("progressBar_correlation")
        self.spinBox_dcdStride = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_dcdStride.setGeometry(QtCore.QRect(150, 380, 62, 24))
        self.spinBox_dcdStride.setMinimum(0)
        self.spinBox_dcdStride.setMaximum(100000)
        self.spinBox_dcdStride.setSingleStep(1)
        self.spinBox_dcdStride.setProperty("value", 1)
        self.spinBox_dcdStride.setObjectName("spinBox_dcdStride")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 270, 109, 21))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 300, 109, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_viewResults = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_viewResults.setEnabled(False)
        self.pushButton_viewResults.setGeometry(QtCore.QRect(540, 410, 251, 61))
        self.pushButton_viewResults.setObjectName("pushButton_viewResults")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 220, 521, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 240, 151, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.doubleSpinBox_soluteDielectric = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_soluteDielectric.setEnabled(True)
        self.doubleSpinBox_soluteDielectric.setGeometry(QtCore.QRect(180, 240, 62, 24))
        self.doubleSpinBox_soluteDielectric.setMaximum(80.0)
        self.doubleSpinBox_soluteDielectric.setProperty("value", 1.0)
        self.doubleSpinBox_soluteDielectric.setObjectName("doubleSpinBox_soluteDielectric")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 30, 71, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("clover.ico"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(620, 30, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_9.setFont(font)
        self.label_9.setAcceptDrops(True)
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.pushButton_loadSampleNAMDdata = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_loadSampleNAMDdata.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.pushButton_loadSampleNAMDdata.setToolTipDuration(10)
        self.pushButton_loadSampleNAMDdata.setStyleSheet("QPushButton {border=1}")
        self.pushButton_loadSampleNAMDdata.setDefault(False)
        self.pushButton_loadSampleNAMDdata.setObjectName("pushButton_loadSampleNAMDdata")
        self.pushButton_loadSampleGMXdata = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_loadSampleGMXdata.setGeometry(QtCore.QRect(280, 10, 241, 31))
        self.pushButton_loadSampleGMXdata.setToolTipDuration(10)
        self.pushButton_loadSampleGMXdata.setFlat(False)
        self.pushButton_loadSampleGMXdata.setObjectName("pushButton_loadSampleGMXdata")
        self.doubleSpinBox_nonbondedCutoff = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_nonbondedCutoff.setEnabled(True)
        self.doubleSpinBox_nonbondedCutoff.setGeometry(QtCore.QRect(460, 240, 62, 24))
        self.doubleSpinBox_nonbondedCutoff.setMaximum(80.0)
        self.doubleSpinBox_nonbondedCutoff.setProperty("value", 12.0)
        self.doubleSpinBox_nonbondedCutoff.setObjectName("doubleSpinBox_nonbondedCutoff")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(260, 240, 191, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "gRINN: Get Residue Interaction Energies"))
        self.doubleSpinBox_filteringCutoff.setToolTip(_translate("MainWindow", "<html><head/><body><p>For a residue pair to be selected for computations, their Centers of Mass (all atoms) must come closer than this value for at least the specified percent of the trajectory frames.</p><p><span style=\" font-weight:600;\">It is advised to keep this value significantly higher than the non-bonded cutoff value used for the simulation.</span></p></body></html>"))
        self.lineEdit_residueGroup1.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Selection 1 and Selection 2 </span><span style=\" font-weight:400;\">define residue groups between which pairwise interaction energies will be computed. Use ProDy Atom Selection syntax.</span></p></body></html>"))
        self.lineEdit_residueGroup1.setText(_translate("MainWindow", "all"))
        self.lineEdit_residueGroup2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Selection 1 and Selection 2 </span>define residue groups between which pairwise interaction energies will be computed. Use ProDy Atom Selection syntax. </p></body></html>"))
        self.lineEdit_residueGroup2.setText(_translate("MainWindow", "all"))
        self.label_4.setText(_translate("MainWindow", "Filtering distance cutoff (Angstroms)"))
        self.label_5.setText(_translate("MainWindow", "Percent cutoff (%)"))
        self.doubleSpinBox_filteringPercent.setToolTip(_translate("MainWindow", "<html><head/><body><p>For a residue pair to be selected for computations, their Centers of Mass must come closer than the filtering distance cutoff value for at least this percent of the trajectory frames.</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Trajectory stride"))
        self.spinBox_numProcessors.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of processors to use for the calculation.</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Number of processors</p></body></html>"))
        self.pushButton_Calculate.setToolTip(_translate("MainWindow", "<html><head/><body><p>Starts the calculation</p></body></html>"))
        self.pushButton_Calculate.setText(_translate("MainWindow", "CALCULATE"))
        self.pushButton_Stop.setToolTip(_translate("MainWindow", "<html><head/><body><p>Stops the calculation. </p><p><br/></p><p>Note: This does not pause the calculation. You have to start over if you click on this button.</p></body></html>"))
        self.pushButton_Stop.setText(_translate("MainWindow", "STOP"))
        self.labelFiltering.setText(_translate("MainWindow", "Filtering progress"))
        self.labelCalculation.setText(_translate("MainWindow", "Calculation progress"))
        self.lineEdit_pdb.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">NAMD Users: </span>Select the Protein Data Bank (PDB) file describing your system here.</p><p><span style=\" font-weight:600;\">Gromacs Users: </span>Select the &quot;run input file&quot; (TPR) that you\'ve used for simulation.</p></body></html>"))
        self.lineEdit_psf.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">NAMD Users: </span>Select the Protein Structure File (PSF) here.</p><p><span style=\" font-weight:600;\">Gromacs Users: </span>Select the topology file (TOP) that you used for simulation.</p></body></html>"))
        self.lineEdit_dcd.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">NAMD Users: </span>Select the DCD file containing your simulation trajectory here.</p><p><span style=\" font-weight:600;\">Gromacs Users: </span>Select the XTC or TRR file containing your simulation trajectory here.</p></body></html>"))
        self.lineEdit_outputFolder.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is the full path to the folder where you wish to store calculation results. </p><p>The path must not exist prior to calculation; it is going to be created by gRINN.</p></body></html>"))
        self.lineEdit_outputFolder.setText(_translate("MainWindow", "grinn_output"))
        self.lineEdit_namd2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the full path to the NAMD or GMX executable here.</p><p>You can just type <span style=\" font-weight:600;\">namd2 </span>or <span style=\" font-weight:600;\">gmx</span>, if the executable<span style=\" font-weight:600;\"/>is already in the executable search path of your system.</p></body></html>"))
        self.lineEdit_namd2.setText(_translate("MainWindow", "namd2"))
        self.pushButton_browsePDB.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">NAMD Users: </span><span style=\" font-weight:400;\">Select the Protein Data Bank (PDB) file describing your system here.</span></p><p><span style=\" font-weight:600;\">Gromacs Users: </span><span style=\" font-weight:400;\">Select the &quot;run input file&quot; (TPR) that you\'ve used for simulation.</span></p></body></html>"))
        self.pushButton_browsePDB.setText(_translate("MainWindow", "Browse for PDB/TPR File"))
        self.pushButton_browsePSF.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">NAMD Users: </span><span style=\" font-weight:400;\">Select the Protein Structure File (PSF) here.</span></p><p><span style=\" font-weight:600;\">Gromacs Users: </span><span style=\" font-weight:400;\">Select the topology file (TOP) that you used for simulation.</span></p></body></html>"))
        self.pushButton_browsePSF.setText(_translate("MainWindow", "Browse for PSF/TOP File"))
        self.pushButton_browseDCD.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">NAMD Users: </span><span style=\" font-weight:400;\">Select the DCD file containing your simulation trajectory here.</span></p><p><span style=\" font-weight:600;\">Gromacs Users: </span><span style=\" font-weight:400;\">Select the XTC or TRR file containing your simulation trajectory here.</span></p></body></html>"))
        self.pushButton_browseDCD.setText(_translate("MainWindow", "Browse for DCD/XTC/TRR File"))
        self.pushButton_browseOutputFolder.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is the full path to the folder where you wish to store calculation results. </p><p>The path must not exist prior to calculation; it is going to be created by gRINN.</p></body></html>"))
        self.pushButton_browseOutputFolder.setText(_translate("MainWindow", "Output Folder"))
        self.pushButton_BrowseNAMD.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the full path to the NAMD or GMX executable here.</p><p>You can just type <span style=\" font-weight:600;\">namd2 </span><span style=\" font-weight:400;\">or </span><span style=\" font-weight:600;\">gmx</span><span style=\" font-weight:400;\">, if the executable</span><span style=\" font-weight:600;\"/><span style=\" font-weight:400;\">is already in the executable search path of your system.</span></p></body></html>"))
        self.pushButton_BrowseNAMD.setText(_translate("MainWindow", "Browse for NAMD/GMX Executable"))
        self.checkBox_interactionCorrelation.setToolTip(_translate("MainWindow", "<html><head/><body><p>Clicking on this checkbox will enable residue interaction energy correlation calculations.</p></body></html>"))
        self.checkBox_interactionCorrelation.setText(_translate("MainWindow", "Calculate residue interaction correlation as well"))
        self.pushButton_BrowseParameterFile.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is the parameter file you used while conducting the NAMD simulation.</p><p>If you have multiple parameter files, you can put them in the same folder and then select all of them in the popup window spawned when you click the &quot;Browse for Parameter File (NAMD)&quot; button.</p></body></html>"))
        self.pushButton_BrowseParameterFile.setText(_translate("MainWindow", "Browse for Parameter File (NAMD)"))
        self.lineEdit_parameterFile.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is the parameter file you used while conducting the NAMD simulation.</p><p><br/></p><p>If you have multiple parameter files, you can put them in the same folder and then select all of them in the popup window spawned when you click the &quot;Browse for Parameter File (NAMD)&quot; button.</p></body></html>"))
        self.doubleSpinBox_AverageIntEnCutoff.setToolTip(_translate("MainWindow", "<html><head/><body><p>Only interactions with the average of absolute interaction energy values above this value will be included in interaction energy correlation calculations.</p></body></html>"))
        self.label_PearsonCorrCutoff.setText(_translate("MainWindow", "Average interaction energy cutoff (kcal/mol)"))
        self.labelCorrelation.setText(_translate("MainWindow", "Correlation progress"))
        self.spinBox_dcdStride.setToolTip(_translate("MainWindow", "<html><head/><body><p>If specified, this value will be applied as a stride to the trajectory frames included in the calculation. For example, if you have 1000 frames in your trajectory and set a value of 10 here, every 10th frame will be selected for calculation, yielding a total of 100 frames.</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Selection 1"))
        self.label_2.setText(_translate("MainWindow", "Selection 2"))
        self.pushButton_viewResults.setText(_translate("MainWindow", "VIEW RESULTS"))
        self.label_8.setText(_translate("MainWindow", "Solute dielectric (NAMD)"))
        self.doubleSpinBox_soluteDielectric.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is the solute dielectric constant used when calculating electrostatic interaction energy with NAMD. A value of 1 describes a vacuum environment. </p><p>Note that electrostatic interactions are computed only in the context of the protein. Solvent molecules are not included in the calculation.</p><p>Also note that this option does not affect the energy calculation using GMX data.</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">gRINN</span></p></body></html>"))
        self.pushButton_loadSampleNAMDdata.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">NAMD Users: </span><span style=\" font-weight:400;\">Select the Protein Data Bank (PDB) file describing your system here.</span></p><p><span style=\" font-weight:600;\">Gromacs Users: </span><span style=\" font-weight:400;\">Select the &quot;run input file&quot; (TPR) that you\'ve used for simulation.</span></p></body></html>"))
        self.pushButton_loadSampleNAMDdata.setText(_translate("MainWindow", "Load sample NAMD data and settings"))
        self.pushButton_loadSampleGMXdata.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">NAMD Users: </span><span style=\" font-weight:400;\">Select the Protein Data Bank (PDB) file describing your system here.</span></p><p><span style=\" font-weight:600;\">Gromacs Users: </span><span style=\" font-weight:400;\">Select the &quot;run input file&quot; (TPR) that you\'ve used for simulation.</span></p></body></html>"))
        self.pushButton_loadSampleGMXdata.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>What is this?</p></body></html>"))
        self.pushButton_loadSampleGMXdata.setText(_translate("MainWindow", "Load sample GMX data and settings"))
        self.doubleSpinBox_nonbondedCutoff.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is the non-bonded interaction cutoff (in Angstroms) for NAMD (the cutoff parameter in NAMD configuration file).</p><p><span style=\" font-weight:600;\">You should set this value to the value you\'ve used for the simulation.</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Non-bonded cutoff (NAMD)"))

