# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultsGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 691)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("clover.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1300, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_Top = QtWidgets.QFrame(self.centralwidget)
        self.frame_Top.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_Top.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_Top.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Top.setObjectName("frame_Top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_Top)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_selectOutputFolder = QtWidgets.QLineEdit(self.frame_Top)
        self.lineEdit_selectOutputFolder.setObjectName("lineEdit_selectOutputFolder")
        self.horizontalLayout_2.addWidget(self.lineEdit_selectOutputFolder)
        self.pushButton_selectOutputFolder = QtWidgets.QPushButton(self.frame_Top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_selectOutputFolder.sizePolicy().hasHeightForWidth())
        self.pushButton_selectOutputFolder.setSizePolicy(sizePolicy)
        self.pushButton_selectOutputFolder.setObjectName("pushButton_selectOutputFolder")
        self.horizontalLayout_2.addWidget(self.pushButton_selectOutputFolder)
        self.pushButton_selectOutputFolder.raise_()
        self.lineEdit_selectOutputFolder.raise_()
        self.verticalLayout_2.addWidget(self.frame_Top)
        self.frame_Main = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_Main.sizePolicy().hasHeightForWidth())
        self.frame_Main.setSizePolicy(sizePolicy)
        self.frame_Main.setMinimumSize(QtCore.QSize(1300, 0))
        self.frame_Main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Main.setObjectName("frame_Main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_Main)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1300, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1000, 0))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_PairwiseEnergies = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_PairwiseEnergies.sizePolicy().hasHeightForWidth())
        self.tab_PairwiseEnergies.setSizePolicy(sizePolicy)
        self.tab_PairwiseEnergies.setMinimumSize(QtCore.QSize(800, 0))
        self.tab_PairwiseEnergies.setMaximumSize(QtCore.QSize(10000000, 10000000))
        self.tab_PairwiseEnergies.setObjectName("tab_PairwiseEnergies")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_PairwiseEnergies)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget_sourceTargetResEnergies = QtWidgets.QTableWidget(self.tab_PairwiseEnergies)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidget_sourceTargetResEnergies.sizePolicy().hasHeightForWidth())
        self.tableWidget_sourceTargetResEnergies.setSizePolicy(sizePolicy)
        self.tableWidget_sourceTargetResEnergies.setMinimumSize(QtCore.QSize(300, 0))
        self.tableWidget_sourceTargetResEnergies.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tableWidget_sourceTargetResEnergies.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_sourceTargetResEnergies.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_sourceTargetResEnergies.setObjectName("tableWidget_sourceTargetResEnergies")
        self.tableWidget_sourceTargetResEnergies.setColumnCount(0)
        self.tableWidget_sourceTargetResEnergies.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tableWidget_sourceTargetResEnergies)
        self.frame_tabPairWiseEnergiesBarPlot = QtWidgets.QFrame(self.tab_PairwiseEnergies)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_tabPairWiseEnergiesBarPlot.sizePolicy().hasHeightForWidth())
        self.frame_tabPairWiseEnergiesBarPlot.setSizePolicy(sizePolicy)
        self.frame_tabPairWiseEnergiesBarPlot.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_tabPairWiseEnergiesBarPlot.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_tabPairWiseEnergiesBarPlot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tabPairWiseEnergiesBarPlot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabPairWiseEnergiesBarPlot.setObjectName("frame_tabPairWiseEnergiesBarPlot")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_tabPairWiseEnergiesBarPlot)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3.addWidget(self.frame_tabPairWiseEnergiesBarPlot)
        self.frame_tabPairWiseEnergiesPlots = QtWidgets.QFrame(self.tab_PairwiseEnergies)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_tabPairWiseEnergiesPlots.sizePolicy().hasHeightForWidth())
        self.frame_tabPairWiseEnergiesPlots.setSizePolicy(sizePolicy)
        self.frame_tabPairWiseEnergiesPlots.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_tabPairWiseEnergiesPlots.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tabPairWiseEnergiesPlots.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabPairWiseEnergiesPlots.setObjectName("frame_tabPairWiseEnergiesPlots")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_tabPairWiseEnergiesPlots)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3.addWidget(self.frame_tabPairWiseEnergiesPlots)
        self.tabWidget.addTab(self.tab_PairwiseEnergies, "")
        self.tab_IEM = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_IEM.sizePolicy().hasHeightForWidth())
        self.tab_IEM.setSizePolicy(sizePolicy)
        self.tab_IEM.setMinimumSize(QtCore.QSize(400, 0))
        self.tab_IEM.setMaximumSize(QtCore.QSize(669, 477))
        self.tab_IEM.setObjectName("tab_IEM")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_IEM)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_tabIEM = QtWidgets.QFrame(self.tab_IEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_tabIEM.sizePolicy().hasHeightForWidth())
        self.frame_tabIEM.setSizePolicy(sizePolicy)
        self.frame_tabIEM.setMinimumSize(QtCore.QSize(400, 400))
        self.frame_tabIEM.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tabIEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabIEM.setObjectName("frame_tabIEM")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_tabIEM)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5.addWidget(self.frame_tabIEM)
        self.verticalSlider_IEM = QtWidgets.QSlider(self.tab_IEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.verticalSlider_IEM.sizePolicy().hasHeightForWidth())
        self.verticalSlider_IEM.setSizePolicy(sizePolicy)
        self.verticalSlider_IEM.setPageStep(1)
        self.verticalSlider_IEM.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_IEM.setObjectName("verticalSlider_IEM")
        self.horizontalLayout_5.addWidget(self.verticalSlider_IEM)
        self.tabWidget.addTab(self.tab_IEM, "")
        self.tab_IEC = QtWidgets.QWidget()
        self.tab_IEC.setObjectName("tab_IEC")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_IEC)
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tableWidget_IEC = QtWidgets.QTableWidget(self.tab_IEC)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidget_IEC.sizePolicy().hasHeightForWidth())
        self.tableWidget_IEC.setSizePolicy(sizePolicy)
        self.tableWidget_IEC.setMinimumSize(QtCore.QSize(500, 0))
        self.tableWidget_IEC.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tableWidget_IEC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_IEC.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_IEC.setObjectName("tableWidget_IEC")
        self.tableWidget_IEC.setColumnCount(0)
        self.tableWidget_IEC.setRowCount(0)
        self.horizontalLayout_7.addWidget(self.tableWidget_IEC)
        self.frame_IECcorrelations = QtWidgets.QFrame(self.tab_IEC)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_IECcorrelations.sizePolicy().hasHeightForWidth())
        self.frame_IECcorrelations.setSizePolicy(sizePolicy)
        self.frame_IECcorrelations.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_IECcorrelations.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_IECcorrelations.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_IECcorrelations.setObjectName("frame_IECcorrelations")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_IECcorrelations)
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_7.addWidget(self.frame_IECcorrelations)
        self.tabWidget.addTab(self.tab_IEC, "")
        self.tab_RC = QtWidgets.QWidget()
        self.tab_RC.setObjectName("tab_RC")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_RC)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_tabRC = QtWidgets.QFrame(self.tab_RC)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_tabRC.sizePolicy().hasHeightForWidth())
        self.frame_tabRC.setSizePolicy(sizePolicy)
        self.frame_tabRC.setMinimumSize(QtCore.QSize(400, 400))
        self.frame_tabRC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tabRC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabRC.setObjectName("frame_tabRC")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_tabRC)
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_8.addWidget(self.frame_tabRC)
        self.tabWidget.addTab(self.tab_RC, "")
        self.tab_Network = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_Network.sizePolicy().hasHeightForWidth())
        self.tab_Network.setSizePolicy(sizePolicy)
        self.tab_Network.setMinimumSize(QtCore.QSize(400, 0))
        self.tab_Network.setObjectName("tab_Network")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_Network)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_NetworkGeneral = QtWidgets.QFrame(self.tab_Network)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_NetworkGeneral.sizePolicy().hasHeightForWidth())
        self.frame_NetworkGeneral.setSizePolicy(sizePolicy)
        self.frame_NetworkGeneral.setMinimumSize(QtCore.QSize(700, 50))
        self.frame_NetworkGeneral.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_NetworkGeneral.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_NetworkGeneral.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_NetworkGeneral.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_NetworkGeneral.setObjectName("frame_NetworkGeneral")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_NetworkGeneral)
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_nwInclCovBonds = QtWidgets.QCheckBox(self.frame_NetworkGeneral)
        self.checkBox_nwInclCovBonds.setChecked(True)
        self.checkBox_nwInclCovBonds.setObjectName("checkBox_nwInclCovBonds")
        self.horizontalLayout_10.addWidget(self.checkBox_nwInclCovBonds, 0, QtCore.Qt.AlignLeft)
        self.label_3 = QtWidgets.QLabel(self.frame_NetworkGeneral)
        self.label_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.doubleSpinBox_nwIntEnCutoff = QtWidgets.QDoubleSpinBox(self.frame_NetworkGeneral)
        self.doubleSpinBox_nwIntEnCutoff.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinBox_nwIntEnCutoff.setProperty("value", 1.0)
        self.doubleSpinBox_nwIntEnCutoff.setObjectName("doubleSpinBox_nwIntEnCutoff")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_nwIntEnCutoff, 0, QtCore.Qt.AlignLeft)
        self.pushButton_updateNetwork = QtWidgets.QPushButton(self.frame_NetworkGeneral)
        self.pushButton_updateNetwork.setObjectName("pushButton_updateNetwork")
        self.horizontalLayout_10.addWidget(self.pushButton_updateNetwork)
        self.pushButton_exportNetwork = QtWidgets.QPushButton(self.frame_NetworkGeneral)
        self.pushButton_exportNetwork.setObjectName("pushButton_exportNetwork")
        self.horizontalLayout_10.addWidget(self.pushButton_exportNetwork)
        self.label_3.raise_()
        self.doubleSpinBox_nwIntEnCutoff.raise_()
        self.checkBox_nwInclCovBonds.raise_()
        self.pushButton_updateNetwork.raise_()
        self.pushButton_exportNetwork.raise_()
        self.verticalLayout_6.addWidget(self.frame_NetworkGeneral, 0, QtCore.Qt.AlignLeft)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_Network)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_ResidueMetrics = QtWidgets.QWidget()
        self.tab_ResidueMetrics.setObjectName("tab_ResidueMetrics")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_ResidueMetrics)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea_Degree = QtWidgets.QScrollArea(self.tab_ResidueMetrics)
        self.scrollArea_Degree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_Degree.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_Degree.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_Degree.setWidgetResizable(True)
        self.scrollArea_Degree.setObjectName("scrollArea_Degree")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 956, 360))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_ResidueMetrics = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_ResidueMetrics.sizePolicy().hasHeightForWidth())
        self.frame_ResidueMetrics.setSizePolicy(sizePolicy)
        self.frame_ResidueMetrics.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_ResidueMetrics.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_ResidueMetrics.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_ResidueMetrics.setObjectName("frame_ResidueMetrics")
        self.horizontalLayout_4.addWidget(self.frame_ResidueMetrics)
        self.scrollArea_Degree.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea_Degree)
        self.frame_2 = QtWidgets.QFrame(self.tab_ResidueMetrics)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_saveResidueMetrics = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_saveResidueMetrics.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_saveResidueMetrics.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pushButton_saveResidueMetrics.setObjectName("pushButton_saveResidueMetrics")
        self.horizontalLayout_9.addWidget(self.pushButton_saveResidueMetrics)
        self.verticalLayout_9.addWidget(self.frame_2, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tabWidget_2.addTab(self.tab_ResidueMetrics, "")
        self.tab_ShortestPaths = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_ShortestPaths.sizePolicy().hasHeightForWidth())
        self.tab_ShortestPaths.setSizePolicy(sizePolicy)
        self.tab_ShortestPaths.setObjectName("tab_ShortestPaths")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_ShortestPaths)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_ShortestPathsTop = QtWidgets.QFrame(self.tab_ShortestPaths)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_ShortestPathsTop.sizePolicy().hasHeightForWidth())
        self.frame_ShortestPathsTop.setSizePolicy(sizePolicy)
        self.frame_ShortestPathsTop.setMinimumSize(QtCore.QSize(500, 10))
        self.frame_ShortestPathsTop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_ShortestPathsTop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_ShortestPathsTop.setObjectName("frame_ShortestPathsTop")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_ShortestPathsTop)
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_ShortestPathsTop)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.comboBox_SourceResidue = QtWidgets.QComboBox(self.frame_ShortestPathsTop)
        self.comboBox_SourceResidue.setObjectName("comboBox_SourceResidue")
        self.horizontalLayout_6.addWidget(self.comboBox_SourceResidue)
        self.label_2 = QtWidgets.QLabel(self.frame_ShortestPathsTop)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.comboBox_TargetResidue = QtWidgets.QComboBox(self.frame_ShortestPathsTop)
        self.comboBox_TargetResidue.setObjectName("comboBox_TargetResidue")
        self.horizontalLayout_6.addWidget(self.comboBox_TargetResidue)
        self.pushButton_findShortestPaths = QtWidgets.QPushButton(self.frame_ShortestPathsTop)
        self.pushButton_findShortestPaths.setObjectName("pushButton_findShortestPaths")
        self.horizontalLayout_6.addWidget(self.pushButton_findShortestPaths)
        self.verticalLayout_7.addWidget(self.frame_ShortestPathsTop)
        self.tableWidget_ShortestPaths = QtWidgets.QTableWidget(self.tab_ShortestPaths)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidget_ShortestPaths.sizePolicy().hasHeightForWidth())
        self.tableWidget_ShortestPaths.setSizePolicy(sizePolicy)
        self.tableWidget_ShortestPaths.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_ShortestPaths.setObjectName("tableWidget_ShortestPaths")
        self.tableWidget_ShortestPaths.setColumnCount(0)
        self.tableWidget_ShortestPaths.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget_ShortestPaths)
        self.tabWidget_2.addTab(self.tab_ShortestPaths, "")
        self.verticalLayout_6.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_Network, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.frame_ProteinViewControl = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_ProteinViewControl.sizePolicy().hasHeightForWidth())
        self.frame_ProteinViewControl.setSizePolicy(sizePolicy)
        self.frame_ProteinViewControl.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_ProteinViewControl.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_ProteinViewControl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_ProteinViewControl.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_ProteinViewControl.setObjectName("frame_ProteinViewControl")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_ProteinViewControl)
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_ProteinView = QtWidgets.QFrame(self.frame_ProteinViewControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_ProteinView.sizePolicy().hasHeightForWidth())
        self.frame_ProteinView.setSizePolicy(sizePolicy)
        self.frame_ProteinView.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_ProteinView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_ProteinView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_ProteinView.setObjectName("frame_ProteinView")
        self.verticalLayout_11.addWidget(self.frame_ProteinView)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_ProteinViewControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_11.addWidget(self.horizontalSlider)
        self.horizontalLayout.addWidget(self.frame_ProteinViewControl)
        self.verticalLayout_4.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.frame_Main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "gRINN: View Results"))
        self.pushButton_selectOutputFolder.setText(_translate("MainWindow", "Select Output Folder"))
        self.tableWidget_sourceTargetResEnergies.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_PairwiseEnergies), _translate("MainWindow", "Pairwise Energies"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_IEM), _translate("MainWindow", "Interaction Energy Matrix"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_IEC), _translate("MainWindow", "Interaction Energy Correlations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_RC), _translate("MainWindow", "Residue Correlation Matrix"))
        self.checkBox_nwInclCovBonds.setText(_translate("MainWindow", "Include covalent bonds as edges"))
        self.label_3.setText(_translate("MainWindow", "Edge addition energy cutoff (kcal/mol):"))
        self.pushButton_updateNetwork.setText(_translate("MainWindow", "Update Network"))
        self.pushButton_exportNetwork.setText(_translate("MainWindow", "Export Network to File..."))
        self.pushButton_saveResidueMetrics.setText(_translate("MainWindow", "Save Residue Metrics to File..."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_ResidueMetrics), _translate("MainWindow", "Residue Metrics"))
        self.label.setText(_translate("MainWindow", "Source Residue"))
        self.label_2.setText(_translate("MainWindow", "Target Residue"))
        self.pushButton_findShortestPaths.setText(_translate("MainWindow", "Find"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_ShortestPaths), _translate("MainWindow", "Shortest Paths"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Network), _translate("MainWindow", "Network Analysis"))

