name: AlloViz
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - python==3.9.* # 3.10 or above provokes numba import fail
  - mdanalysis==2.2.* # 2.3 or above fails with non-complying "formalcharges" last column of PDBs (GPCRmd PDBs)
  - numpy==1.23.*  # 1.24 removed numpy.int and numpy.float needed for dynetan and PyInteraph2
  - ipywidgets==7.* # 8 or above messes with nglview
  - jupyterlab==3.* # 4 or above messes with nglview
  - multiprocess
  - lazyasd
  - pandas
  - pyarrow
  - numba
  - networkx
  - pymol-open-source
  - ambertools
  - nglview
  - prody
  - mdtraj
  - python-louvain
  - compilers
  - cython
  - vmd-python